### ISSUE TITLE
HTML-first (Accessible) Usage?

### ISSUE THREAD

**Issue by jpdevries** [danhunsaker/angular-dynamic-forms#71]
This looks like a really interesting module. I was curious if it was a Node module and could be used on the server side, so that the HTML for the forms could be initially rendered on the page without scripts. It doesn't look like that is the case.

From an accessibility perspective, I'm curious what the best way to handle HTML&ndash;first progressive enhancement would be. Is that something the module should do or more just something people should implement themselves by serving HTML&ndash;first and then overwriting it with dynamic forms?

**Comment by danhunsaker** [comment]
That last one is the only practical approach, here. I built this module for pages in a SPA which would never be accessible on initial page load, so a lot of that wasn't a consideration. Unfortunately, I've also since moved out of front-end dev, so I don't expect to have the chance to really give this project the attention it deserves.

I do have a rather extensive Alternatives section in the README; one of those projects, most of which are both more active and more mature than this one, probably does what you need.
